name: KevinAllen
favicon: null
layout_spectrum: 0.69518
typography_spectrum: 0.34555
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.09736075717955828
  lightness: 0.9844856755807996
  saturation: 0.22539988113567233
  rhythmicContrast: 0.7360774364788085
purpose: []
