name: KevinAllen
favicon: null
layout_spectrum: 0.88127
typography_spectrum: 0.14152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8cbedb'
    - '#1c5c84'
    - '#3e90c3'
    - '#faeee4'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
